// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package pipeline

import "context"

// MapInterface calculate fn(v Interface) to each values from values argument.
// Use ctx to cancel the stream processing.
func MapInterface(
	ctx context.Context,
	fn func(v interface{}) interface{},
	values <-chan interface{},
) <-chan interface{} {
	ch := make(chan interface{})

	go func() {
		defer close(ch)

		for v := range values {
			select {
			case <-ctx.Done():
				return
			case ch <- fn(v):
			}
		}
	}()

	return ch
}

// MapString calculate fn(v String) to each values from values argument.
// Use ctx to cancel the stream processing.
func MapString(
	ctx context.Context,
	fn func(v string) string,
	values <-chan string,
) <-chan string {
	ch := make(chan string)

	go func() {
		defer close(ch)

		for v := range values {
			select {
			case <-ctx.Done():
				return
			case ch <- fn(v):
			}
		}
	}()

	return ch
}

// MapInt calculate fn(v Int) to each values from values argument.
// Use ctx to cancel the stream processing.
func MapInt(
	ctx context.Context,
	fn func(v int) int,
	values <-chan int,
) <-chan int {
	ch := make(chan int)

	go func() {
		defer close(ch)

		for v := range values {
			select {
			case <-ctx.Done():
				return
			case ch <- fn(v):
			}
		}
	}()

	return ch
}

// MapFloat32 calculate fn(v Float32) to each values from values argument.
// Use ctx to cancel the stream processing.
func MapFloat32(
	ctx context.Context,
	fn func(v float32) float32,
	values <-chan float32,
) <-chan float32 {
	ch := make(chan float32)

	go func() {
		defer close(ch)

		for v := range values {
			select {
			case <-ctx.Done():
				return
			case ch <- fn(v):
			}
		}
	}()

	return ch
}
